### ISSUE TITLE
Cars don't change lanes properly when taking off from the highway.

### ISSUE THREAD

**Issue by m-eddington** [OpenDriver2/REDRIVER2#42] opened 2020-11-29 19:16 UTC
Cars intended to go off the highway goes through the obstacle instead of switching lanes earlier.

![REDRIVER2](https://user-images.githubusercontent.com/51070722/100551023-6a8fa900-327e-11eb-997a-e81b1a8aadfc.jpg)

Running the (5.4.123 from appveyor) debug executable in the screenshot but I've seen it happen in 5.3-alpha (linux) as well. Could not replicate this on Retroarch with "Beetle PSX HW (0.9.44.1 9f126e5)" core.

**Comment by SoapyMan** [comment] 2020-11-29 19:20
Yes, that's a known Civ AI bug caused by reverse engineering.
Will gonna look into it as it is a mess

**Comment by SoapyMan** [comment] 2020-12-01 10:36
Fixed in 926cc8c

**Closed by SoapyMan** 2020-12-01 10:36 UTC
Labels: bug
