### ISSUE TITLE
Falling through textures in Havana

### ISSUE THREAD

**Issue by ReTanner2020** [OpenDriver2/REDRIVER2#55] opened 2020-12-04 23:17 UTC
After opening the door of the secret stadium in Havana, it is impossible to drive / walk into the underground garage, the car / Tanner simply falls down through the texture of the ground. CD version is NTSC 1.0

[Proof 1](https://streamable.com/j76jl7)
[Proof 2](https://streamable.com/hjs2ed)

**Comment by SoapyMan** [comment] 2020-12-04 23:20
Are you sure that it's 1.0 version?

**Comment by SoapyMan** [comment] 2020-12-04 23:23
duplicate of #40

**Closed by SoapyMan** 2020-12-04 23:23 UTC
Labels: bug, duplicate

**Comment by ReTanner2020** [comment] 2020-12-05 04:28
![image](https://user-images.githubusercontent.com/75507506/101233784-5824cd80-36cb-11eb-84cb-388080656021.png)
Screen from the emulator console
