### ISSUE TITLE
If you use heavy vehicles when activating the secret car switch, after the door opening cutscene finishes your vehicle will disappear.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#59] opened 2020-12-09 11:44 UTC
When you activate the switch to open the door leading to the secret car, and you happen to use a heavy vehicle like a truck for example, after the small cutscene of the door opening ends your heavy vehicle will be gone.

To test this, for example, in Havana get a bus, a van or a truck, then go to the secret base, leave your heavy vehicle, activate the switch and after the cutscene ends your heavy vehicle will be gone.

This bug also happens in other cities as well, but I noticed that other switches, like the ones to unlock cheats or the hidden tracks in Rio they won't make your heavy vehicle disappear. Only the switches that open the doors of the secret car location will make your heavy vehicle gone.

**Comment by SoapyMan** [comment] 2020-12-09 11:56
This is not a bug and will be not resolved in RERIVERD2. To understand this - there are 4 permanent car slots + 1 dynamic slot (special) which is dynamically reloaded when you drive across regions. Trucks, secret cars and other special cars using that dynamic special slot. Every time you press the secret car door trigger button game will pings out all special cars to be able to load secret car's model and textures into that slot.

**Closed by SoapyMan** 2020-12-09 11:56 UTC
Labels: bug

**Comment by daniel-c910** [comment] 2020-12-09 11:58
Can't this limit be expanded or be fixed at all? Why can't this issue be resolved?

**Comment by SoapyMan** [comment] 2020-12-09 12:03
REDRIVER2 is targeted to be fully backward compatible with PS1 platform (there's gonna be builds for PS1 as well). It is also heavily hardcoded and it will be hard to get working without lots of rework. Those features are getting hold before OpenDriver2 engine which is already planned.

**Comment by SoapyMan** [comment] 2020-12-09 12:04
Also as I pointed out this is not a bug (and really is not an issue), this is how the game works and functions.
